Update xbt

diff --git a/xbt b/xbt
--- a/xbt
+++ b/xbt
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+f#!/usr/bin/env bash
 
 # XBT -- External Backup Tool (v. 3.0) -- by Joe Collins. (www.ezeelinux.com)
 # ...Special Thanks to Jeremy O'Connell and Jody James. (February 18th, 2017)
@@ -38,7 +38,8 @@ if [ ! -d /media/"$user"/XBT_Drive ]; then
     echo "XBT Error: NO XBT DRIVE FOUND! Please make sure XBT_Drive USB is"
     echo "connected. If you just set up the XBT Drive, remove it and plug it"
     echo "back in."
-    greeting
+    greeting()
+
 fi
 
 # Checking for sudo permissions:
@@ -54,9 +55,10 @@ sudo chown "$user" /media/"$user"/XBT_Drive/
 
 # Generate XBT log file file if not there already:
 
-if [ ! -f /media/"$user"/XBT_Drive/XBT_Backups/xbt-backup.log ]; then
-    echo "XBT -- External Backup Tool - Log File" \
-    > /media/"$user"/XBT_Drive/XBT_Backups/xbt-backup.log
+BACKUP=/media/"$user"/XBT_Drive/XBT_Backups/
+
+if [ ! -f "$BACKUP"xbt-backup.log ]; then
+    echo "XBT -- External Backup Tool - Log File" > "$BACKUP"xbt-backup.log
 fi
 
 # Log file is created in /tmp:
@@ -70,7 +72,9 @@ echo "$date_and_time. Any errors?" >> /tmp/backup.log
 
 # Creating machine specific directories:
 
-mkdir -p /media/"$user"/XBT_Drive/XBT_Backups/"$host"
+HOSTLOC=/media/"$user"/XBT_Drive/XBT_Backups/"$host"
+
+mkdir -p "$HOSTLOC"
 
 # Starting synchronization:
 
@@ -80,14 +84,11 @@ echo $'\n'$"Backing up /etc..."
 
 # Checking status of rsync exit code:
 
-if ! sudo rsync -aHv --delete --progress /etc/ \
-/media/"$user"/XBT_Drive/XBT_Backups/"$host"/Etc_Backup/ 2>> /tmp/backup.log; then
+if ! sudo rsync -aHv --delete --progress /etc/ /media/"$user"/XBT_Drive/XBT_Backups/"$host"/Etc_Backup/ 2>> /tmp/backup.log; then
     echo "Starting second pass for /etc..." | tee -a /tmp/backup.log
     
-    if ! sudo rsync -aHv --delete --progress /etc/ \
-    /media/"$user"/XBT_Drive/XBT_Backups/"$host"/Etc_Backup/ 2>> /tmp/backup.log; then
-        echo "...Second pass had some errors errors. Moving on to /home anyway." \
-        | tee -a /tmp/backup.log
+    if ! sudo rsync -aHv --delete --progress /etc/ /media/"$user"/XBT_Drive/XBT_Backups/"$host"/Etc_Backup/ 2>> /tmp/backup.log; then
+        echo "...Second pass had some errors errors. Moving on to /home anyway." | tee -a /tmp/backup.log
         # Set error flag for log file completion:
         local etc_error_code=yes
     fi
@@ -97,14 +98,12 @@ echo $'\n'$"Backing up /home..."
 
 # Checking status of rsync exit code:
 
-if sudo rsync -aHv --delete --progress /home/ \
-/media/"$user"/XBT_Drive/XBT_Backups/"$host"/Home_Backup/ 2>> /tmp/backup.log; then
+if sudo rsync -aHv --delete --progress /home/ /media/"$user"/XBT_Drive/XBT_Backups/"$host"/Home_Backup/ 2>> /tmp/backup.log; then
     echo "Starting second pass for /home..." | tee -a /tmp/backup.log
     
 fi
 
-if sudo rsync -aHv --delete --progress /home/ \
-    /media/"$user"/XBT_Drive/XBT_Backups/"$host"/Home_Backup/ 2>> /tmp/backup.log; then
+if sudo rsync -aHv --delete --progress /home/ /media/"$user"/XBT_Drive/XBT_Backups/"$host"/Home_Backup/ 2>> /tmp/backup.log; then
 
     # Clear any accidental input during backup:
 
@@ -119,8 +118,7 @@ if sudo rsync -aHv --delete --progress /home/ \
     # Report errors with /etc backup if there were any:
 
     if  [ "$etc_error_code" == "yes" ]; then
-        echo "XBT Backup: /home backup successful! Some errors with /etc" \
-        >> /tmp/backup.log
+        echo "XBT Backup: /home backup successful! Some errors with /etc" >> /tmp/backup.log
         echo "Please review XBT Log to see them."
     else
         echo "No errors! :)" >> /tmp/backup.log
@@ -154,14 +152,13 @@ else
         echo "Please review XBT Log to see them."
     fi
 
-    echo "XBT Backup: Backup of /home had errors after two passes at $time!" \
-    | tee -a /tmp/backup.log
+    echo "XBT Backup: Backup of /home had errors after two passes at $time!" | tee -a /tmp/backup.log
     echo "Please review XBT Log to see them."
     cat /tmp/backup.log >> /media/"$user"/XBT_Drive/XBT_Backups/xbt-backup.log
     echo "Wait! Syncing drives..."
     sync
     echo "...Done."
-    greeting
+    greeting()
 
 fi
 
@@ -179,7 +176,7 @@ if [ "$mode" == "CLI" ]; then
     exit
 fi
 
-greeting
+greeting()
 
 }
 
@@ -190,12 +187,11 @@ function restore() {
 # Checking for valid media:
 
 if [ ! -d /media/"$user"/XBT_Drive ]; then
-
     clear
     echo $'\n'$"XBT Restore"
-    echo "XBT Error: NO XBT DRIVE FOUND! Please make sure XBT_Drive USB is connected."
-    greeting
-
+    echo "XBT Error: NO XBT DRIVE FOUND! Please make sure XBT_Drive USB is \
+    connected."
+    greeting()
 fi
 
 # Checking for sudo permissions
@@ -210,12 +206,10 @@ echo $'\n'$"XBT Restore"
 # CHeck for valid media and the host's backup directory:
 
 if [ ! -d /media/"$user"/XBT_Drive/XBT_Backups/"$host"/ ]; then
-
     echo "XBT Error: Cannot find valid backup directory for $host!"
     echo "Drive may not have been used to backup this machine or the"
     echo "XBT_Backups/$host directory may have been moved or deleted."
-    greeting
-
+    greeting()
 fi
 
 echo $'\n'$"WARNING!"$
@@ -223,68 +217,66 @@ echo $'\n'$"Any new files created in /home since last backup WILL BE DELETED!"
 echo "Are you sure you want to restore now? [y/N]"
 read -r -n 1 -s choice
 
-    if "$choice" == "y"; then
+if "$choice" == "y"; then
 
-        # Giving user a chance to close other apps and starting rsync.
+    # Giving user a chance to close other apps and starting rsync.
 
-        echo "Close any running applications and press any key to continue."
+    echo "Close any running applications and press any key to continue."
+    read -r -n 1 -s
+    echo $'\n'$"Restoring /home... Please DO NOT open any applications."
+    
+
+    # Checking status of rsync exit code:
+
+    if sudo rsync -aHv --delete --progress /media/"$user"/XBT_Drive/XBT_Backups/"$host"/Home_Backup/ /home/; then
+
+        # Prompt user to restart machine and exit:
+
+        # Clear any accidental input during restore:
+
+        read -r -t 1 -n 10000 discard
+
+        echo $'\n'$"Restoration complete!"
+        echo "Wait! Syncing drives..."
+        sync
+        echo "...Done."
+        echo "It's now safe to remove XBT_Drive."
+        echo "Restart machine for all changes to take effect."
+        echo $'\n'$"Press any key to exit XBT."
         read -r -n 1 -s
-        echo $'\n'$"Restoring /home... Please DO NOT open any applications."
-        
-
-            # Checking status of rsync exit code:
-
-            if sudo rsync -aHv --delete --progress \
-        /media/"$user"/XBT_Drive/XBT_Backups/"$host"/Home_Backup/ \
-        /home/; then
-
-                # Prompt user to restart machine and exit:
-
-                # Clear any accidental input during restore:
-
-                read -r -t 1 -n 10000 discard
-
-                echo $'\n'$"Restoration complete!"
-                echo "Wait! Syncing drives..."
-                sync
-                echo "...Done."
-                echo "It's now safe to remove XBT_Drive."
-                echo "Restart machine for all changes to take effect."
-                echo $'\n'$"Press any key to exit XBT."
-                read -r -n 1 -s
-                clear
-                echo "Exiting XBT ..Goodbye!"
-                sleep 2
-                tput cnorm
-                exit
-
-            else
-
-                # Returning to Main Menu if rsync fails:
-
-                # Clear any accidental input during restore:
-
-                read -r -t 1 -n 10000 discard
-
-                clear
-                echo $'\n'$"XBT Restore"
-                echo "XBT Error: rsync exited with errors!"
-                echo "DO NOT EXIT XBT UNTIL YOU:"
-                echo $'\n'$"    Make sure XBT Drive USB is still plugged in."
-                echo "    Remount XBT Drive USB by unplugging it and plugging it back in."
-                echo $'\n'$"Wait a few seconds and try running XBT Restore again."
-                echo "You may need to manually restore your data if errors persist."
-                greeting
-
-            fi
+        clear
+        echo "Exiting XBT ..Goodbye!"
+        sleep 2
+        tput cnorm
+        exit
 
     else
 
+        # Returning to Main Menu if rsync fails:
+
+        # Clear any accidental input during restore:
+
+        read -r -t 1 -n 10000 discard
+
         clear
-        echo "XBT restoration canceled."
-        greeting
+        echo $'\n'$"XBT Restore"
+        echo "XBT Error: rsync exited with errors!"
+        echo "DO NOT EXIT XBT UNTIL YOU:"
+        echo $'\n'$"Make sure XBT Drive USB is still plugged in."
+        echo "Remount XBT Drive USB by unplugging it and plugging it back in."
+        echo $'\n'$"Wait a few seconds and try running XBT Restore again."
+        echo "You may need to manually restore your data if errors persist."
+        greeting()
 
     fi
+
+else
+
+    clear
+    echo "XBT restoration canceled."
+    greeting()
+
+fi
 
 # Exit if running from command line:
 
@@ -293,7 +285,7 @@ if [ "$mode" == "CLI" ]; then
 fi
 
 clear
-greeting
+greeting()
 
 }
 
@@ -310,7 +302,7 @@ if [[ ! $(lsblk -S -o  TRAN | grep 'usb') = *usb* ]]; then
     clear
     echo $'\n'$"XBT Drive Setup"
     echo "XBT Error: No valid USB drives to setup! Please plug one in."
-    greeting
+    greeting()
 
 fi
 
@@ -411,7 +403,8 @@ if [ "$choice" == "y" ]; then
 
         # Creating new label and partition:
 
-        sudo parted --script "$chosen_disk" mklabel msdos mkpart primary ext4 1MiB 100%
+        sudo parted --script "$chosen_disk" mklabel msdos mkpart primary \
+        ext4 1MiB 100%
 
         # Creating new ext4 file sysem:
 
@@ -434,7 +427,7 @@ if [ "$choice" == "y" ]; then
         echo $'\n'$"You should now remove the USB dive and plug it back in to"
         echo "make sure that it is property recognized by the system."
         echo "You can then run your first XBT Backup."
-        greeting
+        greeting()
 
     else
 
@@ -442,7 +435,7 @@ if [ "$choice" == "y" ]; then
 
         echo "XBT Drive Setup canceled. $chosen_disk not formatted."; sleep 3
         clear
-        greeting
+        greeting()
 
     fi
 
@@ -451,11 +444,11 @@ else
     # Abort XBT Drive Setup and return to Main Menu:
 
     clear
-    greeting
+    greeting()
 
 fi
 
-greeting
+greeting()
 
 }
 
@@ -482,12 +475,13 @@ if [ ! -d /media/"$user"/XBT_Drive ]; then
 
     # Alert user that XBT Drive is not found:
 
-    echo $'\n'$"USB Status: NO XBT DRIVE FOUND! Please make sure XBT_Drive USB is connected."
+    echo $'\n'$"USB Status: NO XBT DRIVE FOUND! Please make sure XBT_Drive USB"
+    echo "is connected."
     if [[ $(lsblk -S -o  TRAN | grep 'usb') = *usb* ]]; then
 
         # Alert user that drives are connected but no XBT Drive:
 
-        echo "            USB drive(s) connected. Plug in XBT Drive or setup a new one now."
+        echo "USB drive(s) connected. Plug in XBT Drive or setup a new one now."
 
     fi
 
@@ -507,14 +501,14 @@ tput civis
 
 read -r -n 1 -s choice;
     case "$choice" in
-            1) backup;;
-            2) restore;;
-            3) setup_drive;;
-            4) help;;
-            5) log;;
-            6) clear;echo $'\n'$"Refreshing USB Status...";sleep 2;clear;greeting;;
-            0) clear;echo $'\n'$"Exiting XBT... Goodbye!";sleep 2;tput cnorm;exit;;
-            *) echo "Not a valid choice: Please try again.";sleep 2;clear;greeting;;
+        1) backup;;
+        2) restore;;
+        3) setup_drive;;
+        4) help;;
+        5) log;;
+        6) clear;echo $'\n'$"Refreshing USB Status...";sleep 2;clear;greeting;;
+        0) clear;echo $'\n'$"Exiting XBT... Goodbye!";sleep 2;tput cnorm;exit;;
+        *) echo "Not a valid choice: Please try again.";sleep 2;clear;greeting;;
     esac
 
 }
@@ -592,7 +586,7 @@ if [ "$mode" == "CLI" ]; then
 fi
 
 clear
-greeting
+greeting()
 
 }
 
@@ -610,7 +604,7 @@ if [ ! -f /media/"$user"/XBT_Drive/XBT_Backups/xbt-backup.log ]; then
     echo $'\n'$"XBT Log Viewer"
     echo "XBT Error: No log file found. Make sure XBT_Drive USB is connected."
     echo "Note: The log is generated during the first XBT Backup."
-    greeting
+    greeting()
 
 fi
 
@@ -626,7 +620,7 @@ if [ "$mode" == "CLI" ]; then
     exit
 fi
 
-greeting
+greeting()
 
 }
 
@@ -636,28 +630,28 @@ greeting
 
 if [ "$1" == "--help" ]; then
     mode=CLI
-    help
+    help()
 fi
 
 if [ "$1" == "--log" ]; then
     mode=CLI	
-    log
+    log()
 fi
 
 if [ "$1" == "--backup" ]; then
     mode=CLI	
-    backup
+    backup()
 fi
 
 if [ "$1" == "--restore" ]; then
     mode=CLI	
-    restore
+    restore()
 fi
 
 if  [ -n "$1"  ]; then
     echo "XBT Error: Invalid argument. Exiting to Main Menu."
     sleep 3
-    greeting
+    greeting()
 fi
 
 # Greeting user and offering Main Menu:
@@ -665,4 +659,4 @@ fi
 clear
 echo "Greetings and Salutations!"
 
-greeting
+greeting()
